[package]

name = "iron-test"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[lib]

name = "iron-test"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid"

